package pojos;
// Generated Jul 17, 2015 3:49:50 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * JsonTest generated by hbm2java
 */
public class JsonTest  implements java.io.Serializable {


     private int id;
     private Serializable data;

    public JsonTest() {
    }

	
    public JsonTest(int id) {
        this.id = id;
    }
    public JsonTest(int id, Serializable data) {
       this.id = id;
       this.data = data;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getData() {
        return this.data;
    }
    
    public void setData(Serializable data) {
        this.data = data;
    }




}


