package pojos;
// Generated May 28, 2015 12:35:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblBrandColorTheme generated by hbm2java
 */
public class TblBrandColorTheme  implements java.io.Serializable {

     private int id;
     private int brandId;
     private String color1;
     private String color2;
     private String color3;
     private String color4;
     private String color5;
     private boolean customColor;
     private boolean predefined;
     private boolean logo;
     private String themeName;
     private Set tblUserPreferenceses = new HashSet(0);

    public TblBrandColorTheme() {
    }

    public TblBrandColorTheme(int id, int brandId, String color1, String color2, String color3, String color4, String color5, boolean customColor, boolean predefined, boolean logo, String themeName) {
        this.id = id;
        this.brandId = brandId;
        this.color1 = color1;
        this.color2 = color2;
        this.color3 = color3;
        this.color4 = color4;
        this.color5 = color5;
        this.customColor = customColor;
        this.predefined = predefined;
        this.logo = logo;
        this.themeName = themeName;
    }
    public TblBrandColorTheme(int id, int brandId, String color1, String color2, String color3, String color4, String color5, boolean customColor, boolean predefined, boolean logo, String themeName, Set tblUserPreferenceses) {
       this.id = id;
       this.brandId = brandId;
       this.color1 = color1;
       this.color2 = color2;
       this.color3 = color3;
       this.color4 = color4;
       this.color5 = color5;
       this.customColor = customColor;
       this.predefined = predefined;
       this.logo = logo;
       this.themeName = themeName;
       this.tblUserPreferenceses = tblUserPreferenceses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(int brandId) {
        this.brandId = brandId;
    }
    public String getColor1() {
        return this.color1;
    }
    
    public void setColor1(String color1) {
        this.color1 = color1;
    }
    public String getColor2() {
        return this.color2;
    }
    
    public void setColor2(String color2) {
        this.color2 = color2;
    }
    public String getColor3() {
        return this.color3;
    }
    
    public void setColor3(String color3) {
        this.color3 = color3;
    }
    public String getColor4() {
        return this.color4;
    }
    
    public void setColor4(String color4) {
        this.color4 = color4;
    }
    public String getColor5() {
        return this.color5;
    }
    
    public void setColor5(String color5) {
        this.color5 = color5;
    }
    public boolean isCustomColor() {
        return this.customColor;
    }
    
    public void setCustomColor(boolean customColor) {
        this.customColor = customColor;
    }
    public boolean isPredefined() {
        return this.predefined;
    }
    
    public void setPredefined(boolean predefined) {
        this.predefined = predefined;
    }
    public boolean isLogo() {
        return this.logo;
    }
    
    public void setLogo(boolean logo) {
        this.logo = logo;
    }
    public String getThemeName() {
        return this.themeName;
    }
    
    public void setThemeName(String themeName) {
        this.themeName = themeName;
    }
    public Set getTblUserPreferenceses() {
        return this.tblUserPreferenceses;
    }
    
    public void setTblUserPreferenceses(Set tblUserPreferenceses) {
        this.tblUserPreferenceses = tblUserPreferenceses;
    }
}


