package pojos;
// Generated May 28, 2015 12:35:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblBrandFontFamily generated by hbm2java
 */
public class TblBrandFontFamily  implements java.io.Serializable {


     private int id;
     private int brandId;
     private int fontId1;
     private int fontId2;
     private int fontId3;
     private int fontId4;
     private int fontId5;
     private int fontSize1;
     private int fontSize2;
     private int fontSize3;
     private int fontSize4;
     private int fontSize5;
     private int fontStyles1;
     private int fontStyles2;
     private int fontStyles3;
     private int fontStyles4;
     private int fontStyles5;
     private Set tblUserPreferenceses = new HashSet(0);
     private TblBrandPersonality tblBrandPersonality;

    public TblBrandFontFamily() {
    }

	
    public TblBrandFontFamily(int id, int brandId, int fontId1, int fontId2, int fontId3, int fontId4, int fontId5, int fontSize1, int fontSize2, int fontSize3, int fontSize4, int fontSize5, int fontStyles1, int fontStyles2, int fontStyles3, int fontStyles4, int fontStyles5) {
        this.id = id;
        this.brandId = brandId;
        this.fontId1 = fontId1;
        this.fontId2 = fontId2;
        this.fontId3 = fontId3;
        this.fontId4 = fontId4;
        this.fontId5 = fontId5;
        this.fontSize1 = fontSize1;
        this.fontSize2 = fontSize2;
        this.fontSize3 = fontSize3;
        this.fontSize4 = fontSize4;
        this.fontSize5 = fontSize5;
        this.fontStyles1 = fontStyles1;
        this.fontStyles2 = fontStyles2;
        this.fontStyles3 = fontStyles3;
        this.fontStyles4 = fontStyles4;
        this.fontStyles5 = fontStyles5;
    }
    public TblBrandFontFamily(int id, int brandId, int fontId1, int fontId2, int fontId3, int fontId4, int fontId5, int fontSize1, int fontSize2, int fontSize3, int fontSize4, int fontSize5, int fontStyles1, int fontStyles2, int fontStyles3, int fontStyles4, int fontStyles5, Set tblUserPreferenceses, TblBrandPersonality tblBrandPersonality) {
       this.id = id;
       this.brandId = brandId;
       this.fontId1 = fontId1;
       this.fontId2 = fontId2;
       this.fontId3 = fontId3;
       this.fontId4 = fontId4;
       this.fontId5 = fontId5;
       this.fontSize1 = fontSize1;
       this.fontSize2 = fontSize2;
       this.fontSize3 = fontSize3;
       this.fontSize4 = fontSize4;
       this.fontSize5 = fontSize5;
       this.fontStyles1 = fontStyles1;
       this.fontStyles2 = fontStyles2;
       this.fontStyles3 = fontStyles3;
       this.fontStyles4 = fontStyles4;
       this.fontStyles5 = fontStyles5;
       this.tblUserPreferenceses = tblUserPreferenceses;
       this.tblBrandPersonality = tblBrandPersonality;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(int brandId) {
        this.brandId = brandId;
    }
    public int getFontId1() {
        return this.fontId1;
    }
    
    public void setFontId1(int fontId1) {
        this.fontId1 = fontId1;
    }
    public int getFontId2() {
        return this.fontId2;
    }
    
    public void setFontId2(int fontId2) {
        this.fontId2 = fontId2;
    }
    public int getFontId3() {
        return this.fontId3;
    }
    
    public void setFontId3(int fontId3) {
        this.fontId3 = fontId3;
    }
    public int getFontId4() {
        return this.fontId4;
    }
    
    public void setFontId4(int fontId4) {
        this.fontId4 = fontId4;
    }
    public int getFontId5() {
        return this.fontId5;
    }
    
    public void setFontId5(int fontId5) {
        this.fontId5 = fontId5;
    }
    public int getFontSize1() {
        return this.fontSize1;
    }
    
    public void setFontSize1(int fontSize1) {
        this.fontSize1 = fontSize1;
    }
    public int getFontSize2() {
        return this.fontSize2;
    }
    
    public void setFontSize2(int fontSize2) {
        this.fontSize2 = fontSize2;
    }
    public int getFontSize3() {
        return this.fontSize3;
    }
    
    public void setFontSize3(int fontSize3) {
        this.fontSize3 = fontSize3;
    }
    public int getFontSize4() {
        return this.fontSize4;
    }
    
    public void setFontSize4(int fontSize4) {
        this.fontSize4 = fontSize4;
    }
    public int getFontSize5() {
        return this.fontSize5;
    }
    
    public void setFontSize5(int fontSize5) {
        this.fontSize5 = fontSize5;
    }
    public int getFontStyles1() {
        return this.fontStyles1;
    }
    
    public void setFontStyles1(int fontStyles1) {
        this.fontStyles1 = fontStyles1;
    }
    public int getFontStyles2() {
        return this.fontStyles2;
    }
    
    public void setFontStyles2(int fontStyles2) {
        this.fontStyles2 = fontStyles2;
    }
    public int getFontStyles3() {
        return this.fontStyles3;
    }
    
    public void setFontStyles3(int fontStyles3) {
        this.fontStyles3 = fontStyles3;
    }
    public int getFontStyles4() {
        return this.fontStyles4;
    }
    
    public void setFontStyles4(int fontStyles4) {
        this.fontStyles4 = fontStyles4;
    }
    public int getFontStyles5() {
        return this.fontStyles5;
    }
    
    public void setFontStyles5(int fontStyles5) {
        this.fontStyles5 = fontStyles5;
    }
    public Set getTblUserPreferenceses() {
        return this.tblUserPreferenceses;
    }
    
    public void setTblUserPreferenceses(Set tblUserPreferenceses) {
        this.tblUserPreferenceses = tblUserPreferenceses;
    }
    public TblBrandPersonality getTblBrandPersonality() {
        return this.tblBrandPersonality;
    }
    
    public void setTblBrandPersonality(TblBrandPersonality tblBrandPersonality) {
        this.tblBrandPersonality = tblBrandPersonality;
    }




}


