package pojos;
// Generated May 28, 2015 12:35:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblBrandPersonality generated by hbm2java
 */
public class TblBrandPersonality  implements java.io.Serializable {


     private int id;
     private TblBrandFontFamily tblBrandFontFamily;
     private String brandName;
     private Integer lookId;
     private Set tblUserPreferenceses = new HashSet(0);

    public TblBrandPersonality() {
    }

	
    public TblBrandPersonality(TblBrandFontFamily tblBrandFontFamily, String brandName) {
        this.tblBrandFontFamily = tblBrandFontFamily;
        this.brandName = brandName;
    }
    public TblBrandPersonality(TblBrandFontFamily tblBrandFontFamily, String brandName, Integer lookId, Set tblUserPreferenceses) {
       this.tblBrandFontFamily = tblBrandFontFamily;
       this.brandName = brandName;
       this.lookId = lookId;
       this.tblUserPreferenceses = tblUserPreferenceses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TblBrandFontFamily getTblBrandFontFamily() {
        return this.tblBrandFontFamily;
    }
    
    public void setTblBrandFontFamily(TblBrandFontFamily tblBrandFontFamily) {
        this.tblBrandFontFamily = tblBrandFontFamily;
    }
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
    public Integer getLookId() {
        return this.lookId;
    }
    
    public void setLookId(Integer lookId) {
        this.lookId = lookId;
    }
    public Set getTblUserPreferenceses() {
        return this.tblUserPreferenceses;
    }
    
    public void setTblUserPreferenceses(Set tblUserPreferenceses) {
        this.tblUserPreferenceses = tblUserPreferenceses;
    }




}


