package pojos;
// Generated May 28, 2015 12:35:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblCategory generated by hbm2java
 */
public class TblCategory  implements java.io.Serializable {


     private int id;
     private int organizationId;
     private String categoryName;
     private int userId;
     private Set tblModels = new HashSet(0);

    public TblCategory() {
    }

	
    public TblCategory(int id, int organizationId, int userId) {
        this.id = id;
        this.organizationId = organizationId;
        this.userId = userId;
    }
    public TblCategory(int id, int organizationId, String categoryName, int userId, Set tblModels) {
       this.id = id;
       this.organizationId = organizationId;
       this.categoryName = categoryName;
       this.userId = userId;
       this.tblModels = tblModels;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getOrganizationId() {
        return this.organizationId;
    }
    
    public void setOrganizationId(int organizationId) {
        this.organizationId = organizationId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Set getTblModels() {
        return this.tblModels;
    }
    
    public void setTblModels(Set tblModels) {
        this.tblModels = tblModels;
    }




}


