package pojos;
// Generated May 28, 2015 12:35:50 PM by Hibernate Tools 4.3.1



/**
 * TblColors generated by hbm2java
 */
public class TblColors  implements java.io.Serializable {


     private int id;
     private String colorHex;
     private String colorName;

    public TblColors() {
    }

    public TblColors(int id, String colorHex, String colorName) {
       this.id = id;
       this.colorHex = colorHex;
       this.colorName = colorName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getColorHex() {
        return this.colorHex;
    }
    
    public void setColorHex(String colorHex) {
        this.colorHex = colorHex;
    }
    public String getColorName() {
        return this.colorName;
    }
    
    public void setColorName(String colorName) {
        this.colorName = colorName;
    }




}


