package pojos;
// Generated May 28, 2015 12:35:50 PM by Hibernate Tools 4.3.1



/**
 * TblFontSize generated by hbm2java
 */
public class TblFontSize  implements java.io.Serializable {


     private int id;
     private String fontSize;

    public TblFontSize() {
    }

    public TblFontSize(int id, String fontSize) {
       this.id = id;
       this.fontSize = fontSize;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFontSize() {
        return this.fontSize;
    }
    
    public void setFontSize(String fontSize) {
        this.fontSize = fontSize;
    }




}


