package pojos;
// Generated May 28, 2015 12:35:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblLook generated by hbm2java
 */
public class TblLook  implements java.io.Serializable {


     private int id;
     private String lookName;
     private Set tblUserPreferenceses = new HashSet(0);

    public TblLook() {
    }

	
    public TblLook(int id) {
        this.id = id;
    }
    public TblLook(int id, String lookName, Set tblUserPreferenceses) {
       this.id = id;
       this.lookName = lookName;
       this.tblUserPreferenceses = tblUserPreferenceses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLookName() {
        return this.lookName;
    }
    
    public void setLookName(String lookName) {
        this.lookName = lookName;
    }
    public Set getTblUserPreferenceses() {
        return this.tblUserPreferenceses;
    }
    
    public void setTblUserPreferenceses(Set tblUserPreferenceses) {
        this.tblUserPreferenceses = tblUserPreferenceses;
    }




}


