package pojos;
// Generated May 28, 2015 12:35:50 PM by Hibernate Tools 4.3.1



/**
 * TblModelNameValue generated by hbm2java
 */
public class TblModelNameValue  implements java.io.Serializable {


     private int id;
     private int modelId;
     private String name;
     private String value;
     private String defaultValue;
     private String epochFormat;
     private TblModel tblModel;

    public TblModelNameValue() {
    }

	
    public TblModelNameValue(int id, int modelId, String name, String defaultValue) {
        this.id = id;
        this.modelId = modelId;
        this.name = name;
        this.defaultValue = defaultValue;
    }
    public TblModelNameValue(int id, int modelId, String name, String value, String defaultValue, String epochFormat, TblModel tblModel) {
       this.id = id;
       this.modelId = modelId;
       this.name = name;
       this.value = value;
       this.defaultValue = defaultValue;
       this.epochFormat = epochFormat;
       this.tblModel = tblModel;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getModelId() {
        return this.modelId;
    }
    
    public void setModelId(int modelId) {
        this.modelId = modelId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getDefaultValue() {
        return this.defaultValue;
    }
    
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }
    public String getEpochFormat() {
        return this.epochFormat;
    }
    
    public void setEpochFormat(String epochFormat) {
        this.epochFormat = epochFormat;
    }
    public TblModel getTblModel() {
        return this.tblModel;
    }
    
    public void setTblModel(TblModel tblModel) {
        this.tblModel = tblModel;
    }




}


