package pojos;
// Generated May 28, 2015 12:35:50 PM by Hibernate Tools 4.3.1

/**
 * TblModel generated by hbm2java
 */
public class TblModel implements java.io.Serializable {

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    private int id;

    private Integer organization_id;
    private Integer user_id;
    private Integer category_id;
    private String layout_file_name;
    private String model_file_name;
    private String image_url;
    private  String layout_html_data;

    public String getLayout_html_data() {
        return layout_html_data;
    }

    public void setLayout_html_data(String layout_html_data) {
        this.layout_html_data = layout_html_data;
    }

    public String getImage_file_name() {
        return image_file_name;
    }

    public void setImage_file_name(String image_file_name) {
        this.image_file_name = image_file_name;
    }
    private String image_file_name;

  public TblModel() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Integer getOrganization_id() {
        return organization_id;
    }

    public void setOrganization_id(Integer organization_id) {
        this.organization_id = organization_id;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public Integer getCategory_id() {
        return category_id;
    }

    public void setCategory_id(Integer category_id) {
        this.category_id = category_id;
    }

    public String getLayout_file_name() {
        return layout_file_name;
    }

    public void setLayout_file_name(String layout_file_name) {
        this.layout_file_name = layout_file_name;
    }

    public String getModel_file_name() {
        return model_file_name;
    }

    public void setModel_file_name(String model_file_name) {
        this.model_file_name = model_file_name;
    }

    public void setlayout_html_data(String layout_html_data) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


}
