package pojos;
// Generated May 28, 2015 12:35:50 PM by Hibernate Tools 4.3.1

/**
 * TblModel generated by hbm2java
 */
public class TblModel implements java.io.Serializable {

    private int id;
    private TblCategory tblCategory;
    private TblModelNameValue tblModelNameValue;
    private TblOrganization tblOrganization;
    private String modelName;

    public TblModel() {
    }

    public TblModel(TblModelNameValue tblModelNameValue, String modelName) {
        this.tblModelNameValue = tblModelNameValue;
        this.modelName = modelName;
    }

    public TblModel(TblCategory tblCategory, TblModelNameValue tblModelNameValue, TblOrganization tblOrganization, String modelName) {
        this.tblCategory = tblCategory;
        this.tblModelNameValue = tblModelNameValue;
        this.tblOrganization = tblOrganization;
        this.modelName = modelName;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public TblCategory getTblCategory() {
        return this.tblCategory;
    }

    public void setTblCategory(TblCategory tblCategory) {
        this.tblCategory = tblCategory;
    }

    public TblModelNameValue getTblModelNameValue() {
        return this.tblModelNameValue;
    }

    public void setTblModelNameValue(TblModelNameValue tblModelNameValue) {
        this.tblModelNameValue = tblModelNameValue;
    }

    public TblOrganization getTblOrganization() {
        return this.tblOrganization;
    }

    public void setTblOrganization(TblOrganization tblOrganization) {
        this.tblOrganization = tblOrganization;
    }

    public String getModelName() {
        return this.modelName;
    }

    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

}
