package pojos;
// Generated Jul 17, 2015 3:49:50 PM by Hibernate Tools 4.3.1



/**
 * TblSubCategory generated by hbm2java
 */
public class TblSubCategory  implements java.io.Serializable {


     private int id;
     private String externalSource;
     private String externalSourceKeyword;
     private String subCategoryName;
     private String categoryId;

    public TblSubCategory() {
    }

    public TblSubCategory(int id, String externalSource, String externalSourceKeyword, String subCategoryName, String categoryId) {
       this.id = id;
       this.externalSource = externalSource;
       this.externalSourceKeyword = externalSourceKeyword;
       this.subCategoryName = subCategoryName;
       this.categoryId = categoryId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getExternalSource() {
        return this.externalSource;
    }
    
    public void setExternalSource(String externalSource) {
        this.externalSource = externalSource;
    }
    public String getExternalSourceKeyword() {
        return this.externalSourceKeyword;
    }
    
    public void setExternalSourceKeyword(String externalSourceKeyword) {
        this.externalSourceKeyword = externalSourceKeyword;
    }
    public String getSubCategoryName() {
        return this.subCategoryName;
    }
    
    public void setSubCategoryName(String subCategoryName) {
        this.subCategoryName = subCategoryName;
    }
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }




}


