package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * TblBlocks generated by hbm2java
 */
@Entity
@Table(name="tbl_blocks"
    ,schema="public"
)
public class TblBlocks  implements java.io.Serializable {


     private int id;
     private String name;
     private String mindbodyQuery;
     private Integer brandId;
     private Integer subCategoryId;

    public TblBlocks() {
    }

	
    public TblBlocks(int id) {
        this.id = id;
    }
    public TblBlocks(int id, String name, String mindbodyQuery, Integer brandId, Integer subCategoryId) {
       this.id = id;
       this.name = name;
       this.mindbodyQuery = mindbodyQuery;
       this.brandId = brandId;
       this.subCategoryId = subCategoryId;
    }
   
     @Id 

    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="mindbody_query", length=500)
    public String getMindbodyQuery() {
        return this.mindbodyQuery;
    }
    
    public void setMindbodyQuery(String mindbodyQuery) {
        this.mindbodyQuery = mindbodyQuery;
    }

    
    @Column(name="brand_id")
    public Integer getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    
    @Column(name="sub_category_id")
    public Integer getSubCategoryId() {
        return this.subCategoryId;
    }
    
    public void setSubCategoryId(Integer subCategoryId) {
        this.subCategoryId = subCategoryId;
    }




}


