package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * TblBrandColorTheme generated by hbm2java
 */
@Entity
@Table(name="tbl_brand_color_theme"
    ,schema="public"
)
public class TblBrandColorTheme  implements java.io.Serializable {


     private int id;
     private int brandId;
     private String color1;
     private String color2;
     private String color3;
     private String color4;
     private String color5;
     private String color6;
     private Boolean predefined;
     private String themeName;

    public TblBrandColorTheme() {
    }

	
    public TblBrandColorTheme(int id, int brandId, String color1, String color2, String color3, String color4, String color5) {
        this.id = id;
        this.brandId = brandId;
        this.color1 = color1;
        this.color2 = color2;
        this.color3 = color3;
        this.color4 = color4;
        this.color5 = color5;
    }
    public TblBrandColorTheme(int id, int brandId, String color1, String color2, String color3, String color4, String color5, String color6, Boolean predefined, String themeName) {
       this.id = id;
       this.brandId = brandId;
       this.color1 = color1;
       this.color2 = color2;
       this.color3 = color3;
       this.color4 = color4;
       this.color5 = color5;
       this.color6 = color6;
       this.predefined = predefined;
       this.themeName = themeName;
    }
   
     @Id 

//    @GenericGenerator(name="id" , strategy="increment")
//    @GeneratedValue(generator="id")
    
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="brand_id", nullable=false)
    public int getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(int brandId) {
        this.brandId = brandId;
    }

    
    @Column(name="color1", nullable=false, length=30)
    public String getColor1() {
        return this.color1;
    }
    
    public void setColor1(String color1) {
        this.color1 = color1;
    }

    
    @Column(name="color2", nullable=false, length=30)
    public String getColor2() {
        return this.color2;
    }
    
    public void setColor2(String color2) {
        this.color2 = color2;
    }

    
    @Column(name="color3", nullable=false, length=30)
    public String getColor3() {
        return this.color3;
    }
    
    public void setColor3(String color3) {
        this.color3 = color3;
    }

    
    @Column(name="color4", nullable=false, length=30)
    public String getColor4() {
        return this.color4;
    }
    
    public void setColor4(String color4) {
        this.color4 = color4;
    }

    
    @Column(name="color5", nullable=false, length=30)
    public String getColor5() {
        return this.color5;
    }
    
    public void setColor5(String color5) {
        this.color5 = color5;
    }

    
    @Column(name="color6", length=20)
    public String getColor6() {
        return this.color6;
    }
    
    public void setColor6(String color6) {
        this.color6 = color6;
    }

    
    @Column(name="predefined")
    public Boolean getPredefined() {
        return this.predefined;
    }
    
    public void setPredefined(Boolean predefined) {
        this.predefined = predefined;
    }

    
    @Column(name="theme_name", length=30)
    public String getThemeName() {
        return this.themeName;
    }
    
    public void setThemeName(String themeName) {
        this.themeName = themeName;
    }




}


