package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * TblCategory generated by hbm2java
 */
@Entity
@Table(name="tbl_category"
    ,schema="public"
)
public class TblCategory  implements java.io.Serializable {


     private int id;
     private int organizationId;
     private String categoryName;
     private String imageName;

    public TblCategory() {
    }

    public TblCategory(int id, int organizationId, String categoryName, String imageName) {
       this.id = id;
       this.organizationId = organizationId;
       this.categoryName = categoryName;
       this.imageName = imageName;
    }
   
     @Id 

        @GenericGenerator(name="id" , strategy="increment")
    @GeneratedValue(generator="id")

    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="organization_id", nullable=false)
    public int getOrganizationId() {
        return this.organizationId;
    }
    
    public void setOrganizationId(int organizationId) {
        this.organizationId = organizationId;
    }

    
    @Column(name="category_name", nullable=false, length=120)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    
    @Column(name="image_name", nullable=false, length=120)
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }




}


