package com.intbit.marketing.model;
// Generated 19 Oct, 2015 6:43:25 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblColors generated by hbm2java
 */
@Entity
@Table(name="tbl_colors"
    ,schema="public"
)
public class TblColors  implements java.io.Serializable {


     private int id;
     private String colorHex;
     private String colorName;

    public TblColors() {
    }

    public TblColors(int id, String colorHex, String colorName) {
       this.id = id;
       this.colorHex = colorHex;
       this.colorName = colorName;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="color_hex", nullable=false, length=30)
    public String getColorHex() {
        return this.colorHex;
    }
    
    public void setColorHex(String colorHex) {
        this.colorHex = colorHex;
    }

    
    @Column(name="color_name", nullable=false, length=20)
    public String getColorName() {
        return this.colorName;
    }
    
    public void setColorName(String colorName) {
        this.colorName = colorName;
    }




}


