package com.intbit.marketing.model;
// Generated 4 Dec, 2015 4:45:14 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

/**
 * TblEmailDraft generated by hbm2java
 */
@Entity
@Table(name="tbl_email_draft",schema="public")
@TypeDefs( {@TypeDef( name= "StringJsonObject", typeClass = StringJsonUserType.class)})
public class TblEmailDraft  implements java.io.Serializable {


     private int id;
     private Date draftDate;
     private Date editDate;
     private Integer userId;
     private String draftJson;

    public TblEmailDraft() {
    }

	
    public TblEmailDraft(int id) {
        this.id = id;
    }
    public TblEmailDraft(int id, Date draftDate, Integer userId, String draftJson) {
       this.id = id;
       this.draftDate = draftDate;
       this.userId = userId;
       this.draftJson = draftJson;
    }
   
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="draft_date", length=35)
    public Date getDraftDate() {
        return this.draftDate;
    }
    
    public void setDraftDate(Date draftDate) {
        this.draftDate = draftDate;
    }

    
    @Column(name="user_id")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name="draft_json")
    @Type(type = "StringJsonObject")
    public String getDraftJson() {
        return this.draftJson;
    }
    
    public void setDraftJson(String draftJson) {
        this.draftJson = draftJson;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="edit_date", length=35)
    public Date getEditDate() {
        return editDate;
    }

    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }
    
}


