package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblEmailMandrillHistoryId generated by hbm2java
 */
@Embeddable
public class TblEmailMandrillHistoryId  implements java.io.Serializable {


     private int emailHistoryId;
     private String toEmail;

    public TblEmailMandrillHistoryId() {
    }

    public TblEmailMandrillHistoryId(int emailHistoryId, String toEmail) {
       this.emailHistoryId = emailHistoryId;
       this.toEmail = toEmail;
    }
   


    @Column(name="email_history_id", nullable=false)
    public int getEmailHistoryId() {
        return this.emailHistoryId;
    }
    
    public void setEmailHistoryId(int emailHistoryId) {
        this.emailHistoryId = emailHistoryId;
    }


    @Column(name="to_email", nullable=false, length=250)
    public String getToEmail() {
        return this.toEmail;
    }
    
    public void setToEmail(String toEmail) {
        this.toEmail = toEmail;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblEmailMandrillHistoryId) ) return false;
		 TblEmailMandrillHistoryId castOther = ( TblEmailMandrillHistoryId ) other; 
         
		 return (this.getEmailHistoryId()==castOther.getEmailHistoryId())
 && ( (this.getToEmail()==castOther.getToEmail()) || ( this.getToEmail()!=null && castOther.getToEmail()!=null && this.getToEmail().equals(castOther.getToEmail()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmailHistoryId();
         result = 37 * result + ( getToEmail() == null ? 0 : this.getToEmail().hashCode() );
         return result;
   }   


}


