package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblEmailMandrillHistory generated by hbm2java
 */
@Entity
@Table(name="tbl_email_mandrill_history"
    ,schema="public"
)
public class TblEmailMandrillHistory  implements java.io.Serializable {


     private TblEmailMandrillHistoryId id;
     private String mandrillEmailId;
     private String status;
     private String rejectReason;

    public TblEmailMandrillHistory() {
    }

	
    public TblEmailMandrillHistory(TblEmailMandrillHistoryId id) {
        this.id = id;
    }
    public TblEmailMandrillHistory(TblEmailMandrillHistoryId id, String mandrillEmailId, String status, String rejectReason) {
       this.id = id;
       this.mandrillEmailId = mandrillEmailId;
       this.status = status;
       this.rejectReason = rejectReason;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="emailHistoryId", column=@Column(name="email_history_id", nullable=false) ), 
        @AttributeOverride(name="toEmail", column=@Column(name="to_email", nullable=false, length=250) ) } )
    public TblEmailMandrillHistoryId getId() {
        return this.id;
    }
    
    public void setId(TblEmailMandrillHistoryId id) {
        this.id = id;
    }

    
    @Column(name="mandrill_email_id", length=300)
    public String getMandrillEmailId() {
        return this.mandrillEmailId;
    }
    
    public void setMandrillEmailId(String mandrillEmailId) {
        this.mandrillEmailId = mandrillEmailId;
    }

    
    @Column(name="status", length=200)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="reject_reason", length=300)
    public String getRejectReason() {
        return this.rejectReason;
    }
    
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason;
    }




}


