package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * TblFontFamily generated by hbm2java
 */
@Entity
@Table(name="tbl_font_family"
    ,schema="public"
)
public class TblFontFamily  implements java.io.Serializable {


     private int id;
     private String fontName;
     private String fileName;
     private String fontFamilyName;

    public TblFontFamily() {
    }

	
    public TblFontFamily(int id, String fontName) {
        this.id = id;
        this.fontName = fontName;
    }
    public TblFontFamily(int id, String fontName, String fileName, String fontFamilyName) {
       this.id = id;
       this.fontName = fontName;
       this.fileName = fileName;
       this.fontFamilyName = fontFamilyName;
    }
   
     @Id 

    @GenericGenerator(name="id" , strategy="increment")
    @GeneratedValue(generator="id")
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="font_name", nullable=false, length=30)
    public String getFontName() {
        return this.fontName;
    }
    
    public void setFontName(String fontName) {
        this.fontName = fontName;
    }

    
    @Column(name="file_name", length=120)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="font_family_name", length=150)
    public String getFontFamilyName() {
        return this.fontFamilyName;
    }
    
    public void setFontFamilyName(String fontFamilyName) {
        this.fontFamilyName = fontFamilyName;
    }




}


