package com.intbit.marketing.model;
// Generated 19 Oct, 2015 6:43:25 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblFontSize generated by hbm2java
 */
@Entity
@Table(name="tbl_font_size"
    ,schema="public"
)
public class TblFontSize  implements java.io.Serializable {


     private int id;
     private String fontSize;

    public TblFontSize() {
    }

    public TblFontSize(int id, String fontSize) {
       this.id = id;
       this.fontSize = fontSize;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="font_size", nullable=false, length=30)
    public String getFontSize() {
        return this.fontSize;
    }
    
    public void setFontSize(String fontSize) {
        this.fontSize = fontSize;
    }




}


