package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * TblForgotPassword generated by hbm2java
 */
@Entity
@Table(name="tbl_forgot_password"
    ,schema="public"
)
public class TblForgotPassword  implements java.io.Serializable {


     private int id;
     private String userid;
     private String randomlink;
     private Date expdate;
     private Long exptime;

    public TblForgotPassword() {
    }

	
    public TblForgotPassword(int id, String userid, String randomlink, Date expdate) {
        this.id = id;
        this.userid = userid;
        this.randomlink = randomlink;
        this.expdate = expdate;
    }
    public TblForgotPassword(int id, String userid, String randomlink, Date expdate, Long exptime) {
       this.id = id;
       this.userid = userid;
       this.randomlink = randomlink;
       this.expdate = expdate;
       this.exptime = exptime;
    }
   
     @Id 

        @GenericGenerator(name="id" , strategy="increment")
    @GeneratedValue(generator="id")

    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="userid", nullable=false, length=30)
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }

    
    @Column(name="randomlink", nullable=false, length=1000)
    public String getRandomlink() {
        return this.randomlink;
    }
    
    public void setRandomlink(String randomlink) {
        this.randomlink = randomlink;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expdate", nullable=false, length=13)
    public Date getExpdate() {
        return this.expdate;
    }
    
    public void setExpdate(Date expdate) {
        this.expdate = expdate;
    }

    
    @Column(name="exptime")
    public Long getExptime() {
        return this.exptime;
    }
    
    public void setExptime(Long exptime) {
        this.exptime = exptime;
    }




}


