package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * TblFontStyle generated by hbm2java
 */
@Entity
@Table(name="tbl_font_style"
    ,schema="public"
)
public class TblFontStyle  implements java.io.Serializable {


     private int id;
     private String fontStyle;

    public TblFontStyle() {
    }

    public TblFontStyle(int id, String fontStyle) {
       this.id = id;
       this.fontStyle = fontStyle;
    }
   
     @Id 

    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="font_style", nullable=false, length=30)
    public String getFontStyle() {
        return this.fontStyle;
    }
    
    public void setFontStyle(String fontStyle) {
        this.fontStyle = fontStyle;
    }




}


