package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * TblLook generated by hbm2java
 */
@Entity
@Table(name="tbl_look"
    ,schema="public"
)
public class TblLook  implements java.io.Serializable {


     private int id;
     private String lookName;
     private String fileName;
     private Integer organizationId;

    public TblLook() {
    }

	
    public TblLook(int id) {
        this.id = id;
    }
    public TblLook(int id, String lookName, String fileName, Integer organizationId) {
       this.id = id;
       this.lookName = lookName;
       this.fileName = fileName;
       this.organizationId = organizationId;
    }
   
     @Id 

    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="look_name")
    public String getLookName() {
        return this.lookName;
    }
    
    public void setLookName(String lookName) {
        this.lookName = lookName;
    }

    
    @Column(name="file_name", length=80)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="organization_id")
    public Integer getOrganizationId() {
        return this.organizationId;
    }
    
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }




}


