package com.intbit.marketing.model;
// Generated 19 Oct, 2015 6:43:25 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblMarketingCategoryUsersLookup generated by hbm2java
 */
@Entity
@Table(name="tbl_marketing_category_users_lookup"
    ,schema="public"
)
public class TblMarketingCategoryUsersLookup  implements java.io.Serializable {


     private int id;
     private TblMarketingCategory tblMarketingCategory;
     private TblUserLoginDetails tblUserLoginDetails;

    public TblMarketingCategoryUsersLookup() {
    }

	
    public TblMarketingCategoryUsersLookup(int id, TblMarketingCategory tblMarketingCategory) {
        this.id = id;
        this.tblMarketingCategory = tblMarketingCategory;
    }
    public TblMarketingCategoryUsersLookup(int id, TblMarketingCategory tblMarketingCategory, TblUserLoginDetails tblUserLoginDetails) {
       this.id = id;
       this.tblMarketingCategory = tblMarketingCategory;
       this.tblUserLoginDetails = tblUserLoginDetails;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maketing_category_id", nullable=false)
    public TblMarketingCategory getTblMarketingCategory() {
        return this.tblMarketingCategory;
    }
    
    public void setTblMarketingCategory(TblMarketingCategory tblMarketingCategory) {
        this.tblMarketingCategory = tblMarketingCategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public TblUserLoginDetails getTblUserLoginDetails() {
        return this.tblUserLoginDetails;
    }
    
    public void setTblUserLoginDetails(TblUserLoginDetails tblUserLoginDetails) {
        this.tblUserLoginDetails = tblUserLoginDetails;
    }




}


