package com.intbit.marketing.model;
// Generated 19 Oct, 2015 6:43:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblMarketingProgram generated by hbm2java
 */
@Entity
@Table(name="tbl_marketing_program"
    ,schema="public"
)
public class TblMarketingProgram  implements java.io.Serializable {


     private int id;
     private TblMarketingCategory tblMarketingCategory;
     private TblUserLoginDetails tblUserLoginDetails;
     private String name;
     private int order;
     private String htmlData;
     private Set tblMarketingActions = new HashSet(0);

    public TblMarketingProgram() {
    }

	
    public TblMarketingProgram(int id, TblMarketingCategory tblMarketingCategory, String name, int order, String htmlData) {
        this.id = id;
        this.tblMarketingCategory = tblMarketingCategory;
        this.name = name;
        this.order = order;
        this.htmlData = htmlData;
    }
    public TblMarketingProgram(int id, TblMarketingCategory tblMarketingCategory, TblUserLoginDetails tblUserLoginDetails, String name, int order, String htmlData, Set tblMarketingActions) {
       this.id = id;
       this.tblMarketingCategory = tblMarketingCategory;
       this.tblUserLoginDetails = tblUserLoginDetails;
       this.name = name;
       this.order = order;
       this.htmlData = htmlData;
       this.tblMarketingActions = tblMarketingActions;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

   @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="marketing_category_id", nullable=false)
    public TblMarketingCategory getTblMarketingCategory() {
        return this.tblMarketingCategory;
    }
    
    public void setTblMarketingCategory(TblMarketingCategory tblMarketingCategory) {
        this.tblMarketingCategory = tblMarketingCategory;
    }

   @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public TblUserLoginDetails getTblUserLoginDetails() {
        return this.tblUserLoginDetails;
    }
    
    public void setTblUserLoginDetails(TblUserLoginDetails tblUserLoginDetails) {
        this.tblUserLoginDetails = tblUserLoginDetails;
    }

    
    @Column(name="name", nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="order", nullable=false)
    public int getOrder() {
        return this.order;
    }
    
    public void setOrder(int order) {
        this.order = order;
    }

    
    @Column(name="html_data", nullable=false, length=1000)
    public String getHtmlData() {
        return this.htmlData;
    }
    
    public void setHtmlData(String htmlData) {
        this.htmlData = htmlData;
    }






}


