package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * TblMarketingProgram generated by hbm2java
 */
@Entity
@Table(name="tbl_marketing_program"
    ,schema="public"
)
public class TblMarketingProgram  implements java.io.Serializable {


     private int id;
     private TblMarketingCategory tblMarketingCategory;
     private String name;
     private int programOrder;
     private String htmlData;
     private Set tblMarketingActions = new HashSet(0);
     private Set tblMarketingProgramUsersLookups = new HashSet(0);
     private Set tblUserMarketingPrograms = new HashSet(0);

    public TblMarketingProgram() {
    }

	
    public TblMarketingProgram(int id, TblMarketingCategory tblMarketingCategory, String name, int programOrder, String htmlData) {
        this.id = id;
        this.tblMarketingCategory = tblMarketingCategory;
        this.name = name;
        this.programOrder = programOrder;
        this.htmlData = htmlData;
    }
    public TblMarketingProgram(int id, TblMarketingCategory tblMarketingCategory, String name, int programOrder, String htmlData, Set tblMarketingActions, Set tblMarketingProgramUsersLookups, Set tblUserMarketingPrograms) {
       this.id = id;
       this.tblMarketingCategory = tblMarketingCategory;
       this.name = name;
       this.programOrder = programOrder;
       this.htmlData = htmlData;
       this.tblMarketingActions = tblMarketingActions;
       this.tblMarketingProgramUsersLookups = tblMarketingProgramUsersLookups;
       this.tblUserMarketingPrograms = tblUserMarketingPrograms;
    }
   
     @Id 
    @GenericGenerator(name="id" , strategy="increment")
    @GeneratedValue(generator="id")
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="marketing_category_id", nullable=false)
    public TblMarketingCategory getTblMarketingCategory() {
        return this.tblMarketingCategory;
    }
    
    public void setTblMarketingCategory(TblMarketingCategory tblMarketingCategory) {
        this.tblMarketingCategory = tblMarketingCategory;
    }

    
    @Column(name="name", nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="program_order", nullable=false)
    public int getProgramOrder() {
        return this.programOrder;
    }
    
    public void setProgramOrder(int programOrder) {
        this.programOrder = programOrder;
    }

    
    @Column(name="html_data", nullable=false, length=1000)
    public String getHtmlData() {
        return this.htmlData;
    }
    
    public void setHtmlData(String htmlData) {
        this.htmlData = htmlData;
    }






}


