package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * TblModel generated by hbm2java
 */
@Entity
@Table(name="tbl_model"
    ,schema="public"
)
public class TblModel  implements java.io.Serializable {


     private int id;
     private Integer organizationId;
     private Integer userId;
     private Integer categoryId;
     private String layoutFileName;
     private String modelFileName;
     private boolean email;
     private boolean social;
     private Integer subCategoryId;
     private Integer brandId;
     private Integer blockId;
     private String imageFileName;
     private String htmlFileName;
     private String modelName;
     private Boolean media;
     private Boolean print;
     private Boolean download;

    public TblModel() {
    }

	
    public TblModel(int id, String layoutFileName, boolean email, boolean social) {
        this.id = id;
        this.layoutFileName = layoutFileName;
        this.email = email;
        this.social = social;
    }
    public TblModel(int id, Integer organizationId, Integer userId, Integer categoryId, String layoutFileName, String modelFileName, boolean email, boolean social, Integer subCategoryId, Integer brandId, Integer blockId, String imageFileName, String htmlFileName, String modelName, Boolean media, Boolean print, Boolean download) {
       this.id = id;
       this.organizationId = organizationId;
       this.userId = userId;
       this.categoryId = categoryId;
       this.layoutFileName = layoutFileName;
       this.modelFileName = modelFileName;
       this.email = email;
       this.social = social;
       this.subCategoryId = subCategoryId;
       this.brandId = brandId;
       this.blockId = blockId;
       this.imageFileName = imageFileName;
       this.htmlFileName = htmlFileName;
       this.modelName = modelName;
       this.media = media;
       this.print = print;
       this.download = download;
    }
   
     @Id 

        @GenericGenerator(name="id" , strategy="increment")
    @GeneratedValue(generator="id")

    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="organization_id")
    public Integer getOrganizationId() {
        return this.organizationId;
    }
    
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    
    @Column(name="user_id")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="category_id")
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="layout_file_name", nullable=false, length=120)
    public String getLayoutFileName() {
        return this.layoutFileName;
    }
    
    public void setLayoutFileName(String layoutFileName) {
        this.layoutFileName = layoutFileName;
    }

    
    @Column(name="model_file_name", length=120)
    public String getModelFileName() {
        return this.modelFileName;
    }
    
    public void setModelFileName(String modelFileName) {
        this.modelFileName = modelFileName;
    }

    
    @Column(name="email", nullable=false)
    public boolean isEmail() {
        return this.email;
    }
    
    public void setEmail(boolean email) {
        this.email = email;
    }

    
    @Column(name="social", nullable=false)
    public boolean isSocial() {
        return this.social;
    }
    
    public void setSocial(boolean social) {
        this.social = social;
    }

    
    @Column(name="sub_category_id")
    public Integer getSubCategoryId() {
        return this.subCategoryId;
    }
    
    public void setSubCategoryId(Integer subCategoryId) {
        this.subCategoryId = subCategoryId;
    }

    
    @Column(name="brand_id")
    public Integer getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    
    @Column(name="block_id")
    public Integer getBlockId() {
        return this.blockId;
    }
    
    public void setBlockId(Integer blockId) {
        this.blockId = blockId;
    }

    
    @Column(name="image_file_name", length=120)
    public String getImageFileName() {
        return this.imageFileName;
    }
    
    public void setImageFileName(String imageFileName) {
        this.imageFileName = imageFileName;
    }

    
    @Column(name="html_file_name")
    public String getHtmlFileName() {
        return this.htmlFileName;
    }
    
    public void setHtmlFileName(String htmlFileName) {
        this.htmlFileName = htmlFileName;
    }

    
    @Column(name="model_name", length=120)
    public String getModelName() {
        return this.modelName;
    }
    
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    
    @Column(name="media")
    public Boolean getMedia() {
        return this.media;
    }
    
    public void setMedia(Boolean media) {
        this.media = media;
    }

    
    @Column(name="print")
    public Boolean getPrint() {
        return this.print;
    }
    
    public void setPrint(Boolean print) {
        this.print = print;
    }

    
    @Column(name="download")
    public Boolean getDownload() {
        return this.download;
    }
    
    public void setDownload(Boolean download) {
        this.download = download;
    }




}


