package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * TblSubCategory generated by hbm2java
 */
@Entity
@Table(name="tbl_sub_category"
    ,schema="public"
)
public class TblSubCategory  implements java.io.Serializable {


     private int id;
     private String externalSource;
     private String externalSourceKeyword;
     private String subCategoryName;
     private String categoryId;

    public TblSubCategory() {
    }

	
    public TblSubCategory(int id, String externalSourceKeyword, String subCategoryName, String categoryId) {
        this.id = id;
        this.externalSourceKeyword = externalSourceKeyword;
        this.subCategoryName = subCategoryName;
        this.categoryId = categoryId;
    }
    public TblSubCategory(int id, String externalSource, String externalSourceKeyword, String subCategoryName, String categoryId) {
       this.id = id;
       this.externalSource = externalSource;
       this.externalSourceKeyword = externalSourceKeyword;
       this.subCategoryName = subCategoryName;
       this.categoryId = categoryId;
    }
   
     @Id 

        @GenericGenerator(name="id" , strategy="increment")
    @GeneratedValue(generator="id")

    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="external_source", length=120)
    public String getExternalSource() {
        return this.externalSource;
    }
    
    public void setExternalSource(String externalSource) {
        this.externalSource = externalSource;
    }

    
    @Column(name="external_source_keyword", nullable=false, length=120)
    public String getExternalSourceKeyword() {
        return this.externalSourceKeyword;
    }
    
    public void setExternalSourceKeyword(String externalSourceKeyword) {
        this.externalSourceKeyword = externalSourceKeyword;
    }

    
    @Column(name="sub_category_name", nullable=false, length=120)
    public String getSubCategoryName() {
        return this.subCategoryName;
    }
    
    public void setSubCategoryName(String subCategoryName) {
        this.subCategoryName = subCategoryName;
    }

    
    @Column(name="category_id", nullable=false, length=50)
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }




}


