package com.intbit.marketing.model;
// Generated 19 Oct, 2015 6:43:25 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblScheduledEntityTypeColor generated by hbm2java
 */
@Entity
@Table(name="tbl_scheduled_entity_type_color"
    ,schema="public"
)
public class TblScheduledEntityTypeColor  implements java.io.Serializable {


     private String entityType;
     private String color;

    public TblScheduledEntityTypeColor() {
    }

	
    public TblScheduledEntityTypeColor(String entityType) {
        this.entityType = entityType;
    }
    public TblScheduledEntityTypeColor(String entityType, String color) {
       this.entityType = entityType;
       this.color = color;
    }
   
     @Id 

    
    @Column(name="entity_type", unique=true, nullable=false, length=250)
    public String getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    
    @Column(name="color", length=10)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }




}


