package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

/**
 * TblScheduledSocialpostList generated by hbm2java
 */
@Entity
@Table(name="tbl_scheduled_socialpost_list"
    ,schema="public"
)
@TypeDefs( {@TypeDef( name= "StringJsonObject", typeClass = StringJsonUserType.class)})
public class TblScheduledSocialpostList  implements java.io.Serializable {


     private int id;
     private Integer userId;
     private String imageName;
     private String tokenData;
     private String metadata;
     private String type;
     private TblScheduledEntityList tblScheduledEntityList;

    public TblScheduledSocialpostList() {
    }

	
    public TblScheduledSocialpostList(int id) {
        this.id = id;
    }
    public TblScheduledSocialpostList(int id, Integer userId, String imageName, String tokenData, String metadata, String type,TblScheduledEntityList tblScheduledEntityList) {
       this.id = id;
       this.userId = userId;
       this.imageName = imageName;
       this.tokenData = tokenData;
       this.metadata = metadata;
       this.type = type;
       this.tblScheduledEntityList = tblScheduledEntityList;
    }
   
     @Id 

    @GenericGenerator(name="id" , strategy="increment")
    @GeneratedValue(generator="id")

    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="user_id")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="image_name", length=250)
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    
    @Column(name="token_data")
    @Type(type = "StringJsonObject")
    public String getTokenData() {
        return this.tokenData;
    }
    
    public void setTokenData(String tokenData) {
        this.tokenData = tokenData;
    }

    
    @Column(name="metadata")
    @Type(type = "StringJsonObject")
    public String getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(String metadata) {
        this.metadata = metadata;
    }

    
    @Column(name="type", length=250)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

     @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entity_list_id")
    public TblScheduledEntityList getTblScheduledEntityList() {
        return this.tblScheduledEntityList;
    }
    
    public void setTblScheduledEntityList(TblScheduledEntityList tblScheduledEntityList) {
        this.tblScheduledEntityList = tblScheduledEntityList;
    }


}


