package com.intbit.marketing.model;
// Generated 30 Oct, 2015 3:41:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblScheduledTwitter generated by hbm2java
 */
@Entity
@Table(name="tbl_scheduled_twitter"
    ,schema="public"
)
public class TblScheduledTwitter  implements java.io.Serializable {


     private int id;
     private TblScheduledSocialpostList tblScheduledSocialpostList;
     private Date datetime;

    public TblScheduledTwitter() {
    }

	
    public TblScheduledTwitter(int id) {
        this.id = id;
    }
    public TblScheduledTwitter(int id, TblScheduledSocialpostList tblScheduledSocialpostList, Date datetime) {
       this.id = id;
       this.tblScheduledSocialpostList = tblScheduledSocialpostList;
       this.datetime = datetime;
    }
   
     @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="schedule_social_id")
    public TblScheduledSocialpostList getTblScheduledSocialpostList() {
        return this.tblScheduledSocialpostList;
    }
    
    public void setTblScheduledSocialpostList(TblScheduledSocialpostList tblScheduledSocialpostList) {
        this.tblScheduledSocialpostList = tblScheduledSocialpostList;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="datetime", length=21)
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }




}


