package com.intbit.marketing.model;
// Generated 19 Oct, 2015 6:43:25 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblScheduledSocialpostList generated by hbm2java
 */
@Entity
@Table(name="tbl_scheduled_socialpost_list"
    ,schema="public"
)
public class TblScheduledSocialpostList  implements java.io.Serializable {


     private int id;
     private Integer userId;
     private String imageName;
     private Serializable tokenData;
     private Serializable metadata;
     private String type;

    public TblScheduledSocialpostList() {
    }

	
    public TblScheduledSocialpostList(int id) {
        this.id = id;
    }
    public TblScheduledSocialpostList(int id, Integer userId, String imageName, Serializable tokenData, Serializable metadata, String type) {
       this.id = id;
       this.userId = userId;
       this.imageName = imageName;
       this.tokenData = tokenData;
       this.metadata = metadata;
       this.type = type;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="user_id")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="image_name", length=250)
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    
    @Column(name="token_data")
    public Serializable getTokenData() {
        return this.tokenData;
    }
    
    public void setTokenData(Serializable tokenData) {
        this.tokenData = tokenData;
    }

    
    @Column(name="metadata")
    public Serializable getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(Serializable metadata) {
        this.metadata = metadata;
    }

    
    @Column(name="type", length=250)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


