package com.intbit.marketing.model;
// Generated 19 Oct, 2015 6:43:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUserMarketingProgram generated by hbm2java
 */
@Entity
@Table(name="tbl_user_marketing_program"
    ,schema="public"
)
public class TblUserMarketingProgram  implements java.io.Serializable {


     private int id;
     private TblUserLoginDetails tblUserLoginDetails;
     private String name;
     private Date dateEvent;
     private Date createDate;
     private Set tblScheduledEntityLists = new HashSet(0);

    public TblUserMarketingProgram() {
    }

	
    public TblUserMarketingProgram(int id) {
        this.id = id;
    }
    public TblUserMarketingProgram(int id, TblUserLoginDetails tblUserLoginDetails, String name, Date dateEvent, Date createDate, Set tblScheduledEntityLists) {
       this.id = id;
       this.tblUserLoginDetails = tblUserLoginDetails;
       this.name = name;
       this.dateEvent = dateEvent;
       this.createDate = createDate;
       this.tblScheduledEntityLists = tblScheduledEntityLists;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public TblUserLoginDetails getTblUserLoginDetails() {
        return this.tblUserLoginDetails;
    }
    
    public void setTblUserLoginDetails(TblUserLoginDetails tblUserLoginDetails) {
        this.tblUserLoginDetails = tblUserLoginDetails;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_event", length=29)
    public Date getDateEvent() {
        return this.dateEvent;
    }
    
    public void setDateEvent(Date dateEvent) {
        this.dateEvent = dateEvent;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=29)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }






}


