package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * TblUserLoginDetails generated by hbm2java
 */
@Entity
@Table(name="tbl_user_login_details"
    ,schema="public"
)
public class TblUserLoginDetails  implements java.io.Serializable {


     private int id;
     private String userName;
     private String password;
     private int organizationid;
     private String logoName;
     private String companyName;
     private Set tblScheduledEmailLists = new HashSet(0);
     private Set tblUserMarketingPrograms = new HashSet(0);
     private Set tblMarketingCategoryUsersLookups = new HashSet(0);
     private Set tblMarketingProgramUsersLookups = new HashSet(0);

    public TblUserLoginDetails() {
    }

	
    public TblUserLoginDetails(int id, String userName, String password, int organizationid, String logoName) {
        this.id = id;
        this.userName = userName;
        this.password = password;
        this.organizationid = organizationid;
        this.logoName = logoName;
    }
    public TblUserLoginDetails(int id, String userName, String password, int organizationid, String logoName, String companyName, Set tblScheduledEmailLists, Set tblUserMarketingPrograms, Set tblMarketingCategoryUsersLookups, Set tblMarketingProgramUsersLookups) {
       this.id = id;
       this.userName = userName;
       this.password = password;
       this.organizationid = organizationid;
       this.logoName = logoName;
       this.companyName = companyName;
       this.tblScheduledEmailLists = tblScheduledEmailLists;
       this.tblUserMarketingPrograms = tblUserMarketingPrograms;
       this.tblMarketingCategoryUsersLookups = tblMarketingCategoryUsersLookups;
       this.tblMarketingProgramUsersLookups = tblMarketingProgramUsersLookups;
    }
   
     @Id 
    @GenericGenerator(name="id" , strategy="increment")
    @GeneratedValue(generator="id")

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="user_name", nullable=false, length=30)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="organizationid", nullable=false)
    public int getOrganizationid() {
        return this.organizationid;
    }
    
    public void setOrganizationid(int organizationid) {
        this.organizationid = organizationid;
    }

    
    @Column(name="logo_name", nullable=false, length=120)
    public String getLogoName() {
        return this.logoName;
    }
    
    public void setLogoName(String logoName) {
        this.logoName = logoName;
    }

    
    @Column(name="company_name", length=120)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }



}


