package com.intbit.marketing.model;
// Generated Oct 28, 2015 12:01:09 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

/**
 * TblUserPreferences generated by hbm2java
 */
@Entity
@Table(name="tbl_user_preferences"
    ,schema="public"
)
@TypeDefs( {@TypeDef( name= "StringJsonObject", typeClass = StringJsonUserType.class)})
public class TblUserPreferences  implements java.io.Serializable {


     private int id;
     private TblBrandFontFamily tblBrandFontFamily;
     private TblBrandPersonality tblBrandPersonality;
     private int userId;
     private String location;
     private int lookId;
     private String userPreferences;
     private String mindbodyEmailList;

    public TblUserPreferences() {
    }

	
    public TblUserPreferences(int id, TblBrandFontFamily tblBrandFontFamily, TblBrandPersonality tblBrandPersonality, int userId, String location, int lookId) {
        this.id = id;
        this.tblBrandFontFamily = tblBrandFontFamily;
        this.tblBrandPersonality = tblBrandPersonality;
        this.userId = userId;
        this.location = location;
        this.lookId = lookId;
    }
    public TblUserPreferences(int id, TblBrandFontFamily tblBrandFontFamily, TblBrandPersonality tblBrandPersonality, int userId, String location, int lookId, String userPreferences, String mindbodyEmailList) {
       this.id = id;
       this.tblBrandFontFamily = tblBrandFontFamily;
       this.tblBrandPersonality = tblBrandPersonality;
       this.userId = userId;
       this.location = location;
       this.lookId = lookId;
       this.userPreferences = userPreferences;
       this.mindbodyEmailList = mindbodyEmailList;
    }
   
    @Id 

    @GenericGenerator(name="id" , strategy="increment")
    @GeneratedValue(generator="id")
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="font_theme_id", nullable=false)
    public TblBrandFontFamily getTblBrandFontFamily() {
        return this.tblBrandFontFamily;
    }
    
    public void setTblBrandFontFamily(TblBrandFontFamily tblBrandFontFamily) {
        this.tblBrandFontFamily = tblBrandFontFamily;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="brand_id", nullable=false)
    public TblBrandPersonality getTblBrandPersonality() {
        return this.tblBrandPersonality;
    }
    
    public void setTblBrandPersonality(TblBrandPersonality tblBrandPersonality) {
        this.tblBrandPersonality = tblBrandPersonality;
    }

    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="location", nullable=false, length=30)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="look_id", nullable=false)
    public int getLookId() {
        return this.lookId;
    }
    
    public void setLookId(int lookId) {
        this.lookId = lookId;
    }

    
    @Column(name="user_preferences")
     @Type(type = "StringJsonObject")
    public String getUserPreferences() {
        return this.userPreferences;
    }
    
    public void setUserPreferences(String userPreferences) {
        this.userPreferences = userPreferences;
    }

    
    @Column(name="mindbody_email_list")
     @Type(type = "StringJsonObject")
    public String getMindbodyEmailList() {
        return this.mindbodyEmailList;
    }
    
    public void setMindbodyEmailList(String mindbodyEmailList) {
        this.mindbodyEmailList = mindbodyEmailList;
    }




}


